// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA010PvNKihdJ3VMMphx56roLL0LfKZML0',
    appId: '1:545750551468:web:086ad840f5eaef0ecb4809',
    messagingSenderId: '545750551468',
    projectId: 'my-project-lectura',
    authDomain: 'my-project-lectura.firebaseapp.com',
    storageBucket: 'my-project-lectura.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq8SRo4a-XrlSFijFqwNGeP101PdMO82s',
    appId: '1:545750551468:android:2bb41b80de99f56ecb4809',
    messagingSenderId: '545750551468',
    projectId: 'my-project-lectura',
    storageBucket: 'my-project-lectura.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANuVDa-jO1EEA-bj02p9mQd9yYPeuGzZ8',
    appId: '1:545750551468:ios:a207bee37786ad4fcb4809',
    messagingSenderId: '545750551468',
    projectId: 'my-project-lectura',
    storageBucket: 'my-project-lectura.firebasestorage.app',
    iosBundleId: 'com.example.proyectoLenguaje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANuVDa-jO1EEA-bj02p9mQd9yYPeuGzZ8',
    appId: '1:545750551468:ios:a207bee37786ad4fcb4809',
    messagingSenderId: '545750551468',
    projectId: 'my-project-lectura',
    storageBucket: 'my-project-lectura.firebasestorage.app',
    iosBundleId: 'com.example.proyectoLenguaje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA010PvNKihdJ3VMMphx56roLL0LfKZML0',
    appId: '1:545750551468:web:23d454622aa4a8d8cb4809',
    messagingSenderId: '545750551468',
    projectId: 'my-project-lectura',
    authDomain: 'my-project-lectura.firebaseapp.com',
    storageBucket: 'my-project-lectura.firebasestorage.app',
  );
}
